name: "Feature request"
description: "Suggest an idea for this project"
labels: "enhancement"
body:
- type: textarea
  attributes:
    label: "Explain the feature"
    description: "Give a clear and concise description of what should be added."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Justification"
    description: "Give a clear and concise explanation of why this should be added."
  validations:
    required: false
